THEOS_DEVICE_IP=192.168.1.101
include theos/makefiles/common.mk

TOOL_NAME = Evernote2myblogd

Evernote2myblogd_FILES = main.mm Evernote2myBlogd.m
Evernote2myblogd_FRAMEWORKS = CoreFoundation SystemConfiguration
Evernote2myblogd_PRIVATE_FRAMEWORKS = AppSupport
Evernote2myblogd_LIBRARIES = rocketbootstrap

include $(THEOS_MAKE_PATH)/tool.mk
